language: python
python: "3.6"
script: make trades deploy

# This is implicit
# pip install -r requirements
#
deploy:
  provider: pages
  github-token: ${github_token}
  skip-cleanup: true
  on:
    branch: master
