language: python
python: "3.6"
script: make all deploy

# This is implicit
# pip install -r requirements
#
deploy:
  provider: pages
  github-token: ${api-key}
  skip-cleanup: true
  on:
    branch: master
